### ISSUE TITLE
Output git logs to `docker logs $munki-d`

### ISSUE THREAD

**Issue by wegotoeleven** [grahampugh/munki-do#17]
At present, the only logs visible when using docker logs munki-do are web server access logs. Would it be possible to output Git logs also?

**Comment by wegotoeleven** [comment]
At present, the only logs visible when using `docker logs munki-do` are web server access logs. Would it be possible to output Git logs also?

**Comment by grahampugh** [comment]
`docker logs munki-do` now shows all the logged output from django. This was achieved by adding `RUN ln -sf /dev/stdout /var/log/django/info.log` to the `Dockerfile`.
